<p>{{SolutionName}} requires that all persons or entities visiting any {{SolutionName}} Sites on the World Wide Web (&quot;Sites&quot;) agree to the following terms and conditions.&nbsp; By accessing a Site, you confirm your agreement to and acceptance of these terms.</p>
<p><b>Use of Information</b><br />
Unless otherwise specified, copyright in all copyrightable subject matter on any Site is owned by {{SolutionName}}. To the extent that {{SolutionName}} have the right to do so without compensation to third parties, and except for materials or information specifically provided under other terms, {{SolutionName}} grants you permission to copy or otherwise download from any Site, information and materials (including related graphics), provided: 1. The materials are for internal, non-commercial use only, and 2. Any copies of materials or portions thereof must include the copyright notice specified on the Site.</p>
<p>If attribution to {{SolutionName}} is included, limited quotations from the content are hereby permitted. You may not copy or display for redistribution to third parties for commercial purposes any portion of the content without the prior written permission of {{SolutionName}}.</p>
<p>Documents posted by {{SolutionName}} on a Site may contain other proprietary notices or describe products, services, processes or technologies owned by {{SolutionName}} or third parties. Nothing contained herein shall be construed by implication, estoppels or otherwise as granting to the user a license under any copyright, trademark, patent or other intellectual property right of {{SolutionName}} or any third party.</p>
<p><b>Trademarks</b><br />
The {{SolutionName}} name and logo and all related product and service names, design marks and slogans are trademarks, service marks or registered trademarks of {{SolutionName}} and may not be used in any manner without the prior written consent of {{SolutionName}}. Other products and service marks are trademarks of their respective owners.</p>
<p><b>Consent to Monitoring and Disclosure</b><br />
{{SolutionName}} is under no obligation to monitor the information residing or transmitted to this site. However, anyone accessing this site agrees that {{SolutionName}} may monitor the site to (1) comply with any necessary laws, regulations or governmental requests; (2) to, in its sole discretion, operate the Site in a manner it deems proper or to protect against conduct it deems inappropriate. {{SolutionName}} shall have the right but not the obligation, to reject or eliminate any information residing on or transmitted to the Site that it, in its sole discretion, believes is unacceptable or inconsistent with these terms and conditions.</p>
<p>In the event {{SolutionName}} receives information or materials through the Site, including but not limited to feedback, data, answers, questions, comments, suggestions, plans, ideas or the like, such information or material shall be deemed to be non-confidential and {{SolutionName}} assumes no obligation to protect same from disclosure. The submission of information or materials to {{SolutionName}} shall in no way prevent the purchase, manufacture or use of similar products, services, plans and ideas by {{SolutionName}} for any purpose whatever. In addition, you grant {{SolutionName}} the right, in any form now or hereafter known, to reproduce, use, disclose, distribute, transmit, create derivative works from, and publicly display and perform, any information or materials you submit to through any Site.</p>
<p><b>Limitation of Liability</b><br />
You assume all responsibility and risk for the use of this site and the Internet generally. In no event shall {{SolutionName}} or Bookt, LLC, &nbsp; or its affiliates be liable for any direct, special, indirect, or consequential damages or any damages whatsoever; including but not limited to loss of use, data, or profits, without regard to the form of any action, including but not limited to contract, negligence, or other tort actions, arising out of or in connection with the use, copying, or display of the content resulting from access to or use of this site, or the Internet generally, under contract, tort or any other cause of action or legal theory.</p>
<p>Although {{SolutionName}} believes the content to be accurate, complete, and current, {{SolutionName}} makes no warranty as to the accuracy, completeness or currency of the content. It is your responsibility to verify any information before relying on it. The content of this site may include technical inaccuracies or typographical errors. From time to time, changes are made to the content herein. {{SolutionName}} may make changes in the products and/or the services described herein at any time.</p>
<p><b>Warranty Disclaimer</b><br />
Access to each site (including any information or materials therein) is provided on an &quot;as is&quot; basis, without warranties of any kind, either express or implied, including, but not limited to, warranties of title, non infringement or implied warranties of merchantability or fitness for a particular purpose. No advice or information given by {{SolutionName}}, affiliates or their respective employees shall create any warranty. Neither {{SolutionName}}, nor its affiliates warrant that the information or materials on, or access to, any site will be without interruption or error free.</p>
<p><b>Endorsements and Linked Sites</b><br />
Some of the sites listed as links herein are not under the control of {{SolutionName}}. Accordingly, {{SolutionName}} makes no representations whatsoever concerning the content of those sites. The fact that {{SolutionName}} have provided a link to a site is NOT an endorsement, authorization, sponsorship, or affiliation by {{SolutionName}} with respect to such site, its owners, or its providers. {{SolutionName}} is providing these links only as a convenience to you. RECHANNEL has not tested any information, software, or products found on these sites and therefore cannot make any representations whatsoever with respect thereto. There are risks in using any information, software, or products found on the Internet; and {{SolutionName}} cautions you to make sure that you completely understand these risks before retrieving, using, relying upon, or purchasing anything via the Internet.</p>
<p><b>Security</b><br />
You agree that you will comply with any security processes and procedures (such as passwords) specified by {{SolutionName}} with respect to access to or use of the Site. Further, you agree not to access or attempt to access any areas of or through a Site which are not intended for general public access, unless you have been provided with explicit written authorization to do so by {{SolutionName}}.</p>
<p><b>Changes and Other Terms</b><br />
{{SolutionName}} have the right to make changes and updates to any information contained within this site without prior notice. {{SolutionName}} reserves the right to change any of the Terms of Use without prior notice. Access to particular areas on the site may be subject to additional or different terms and conditions, as specified by {{SolutionName}} from time to time.</p>
<p><b>Failure to Comply</b><br />
{{SolutionName}} have the right to terminate or restrict your access to any or all Sites, unilaterally and without notice, in the event you violate any of these Terms of Use. {{SolutionName}} also reserves any and all remedies at law or equity in connection with violation of these Terms of Use.</p>
<p><b>Information Provided by You </b><br />
Any information provided by you to {{SolutionName}}, including but not limited to feedback, data, questions, comments, suggestions, or the like, shall be deemed to be non confidential. {{SolutionName}} shall have no obligation of any kind with respect to such information and shall be free to reproduce, use, disclose, and distribute the information to others without limitation.</p>
<p>Additionally, {{SolutionName}} shall be free to use any ideas, concepts, know-how or techniques contained in such information for any purpose whatsoever, including but not limited to developing, manufacturing, and marketing products incorporating such information.</p>